spring:
    datasource:
        url: jdbc:postgresql://db.fuhioaxgexonukldatsp.supabase.co:5432/postgres?user=postgres&password=65y%2AMJeBXL9VDn-
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 1
            minimum-idle: 0
            idle-timeout: 5000
            connection-timeout: 5000
            max-lifetime: 180000
            leak-detection-threshold: 10000
            auto-commit: true
            connection-test-query: SELECT 1
            validation-timeout: 1000
            initialization-fail-timeout: 0

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
                connection:
                    provider_disables_autocommit: true
                current_session_context_class: thread
                enable_lazy_load_no_trans: true
        open-in-view: false
        defer-datasource-initialization: true

    mvc:
        cors:
            allowed-origins: ${CORS_ALLOWED_ORIGINS:https://shop-tiqaktmxj.vercel.app,https://shop-tiqaktmxj-dfp3ekhhx-memoriz2s-projects.vercel.app}
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

    security:
        jwt:
            secret: your-secret-key
            expiration: 86400000 # 24시간

server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: never
        include-exception: false
    tomcat:
        threads:
            max: 200
            min-spare: 20
        connection-timeout: 2000
        max-connections: 10000
        accept-count: 100
        max-keep-alive-requests: 100

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        com.shop: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
