spring:
    # datasource:
    #     url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    #     username: postgres.jjincmywoeciknaxnplg
    #     password: "#jwX6?wpJRe!&LB"
    #     driver-class-name: org.postgresql.Driver
    #     hikari:
    #         connection-timeout: 3000
    #         maximum-pool-size: 5
    #         minimum-idle: 1
    #         idle-timeout: 10000
    #         max-lifetime: 300000
    #         auto-commit: true
    #         pool-name: HikariCP
    #         validation-timeout: 1000
    #         leak-detection-threshold: 5000
    #         connection-test-query: SELECT 1
    #         initialization-fail-timeout: 0

    # jpa:
    #     hibernate:
    #         ddl-auto: update
    #     show-sql: false
    #     open-in-view: false
    #     properties:
    #         hibernate:
    #             format_sql: false
    #             dialect: org.hibernate.dialect.PostgreSQLDialect
    #             jdbc:
    #                 batch_size: 100
    #                 batch_versioned_data: true
    #             order_inserts: true
    #             order_updates: true
    #             generate_statistics: false
    #             connection:
    #                 provider_disables_autocommit: false

    security:
        jwt:
            secret: your-secret-key
            expiration: 86400000 # 24시간

server:
    port: 8080
    tomcat:
        threads:
            max: 200
            min-spare: 20
        connection-timeout: 2000
        max-connections: 10000
        accept-count: 100
        max-keep-alive-requests: 100

logging:
    level:
        root: WARN
        org.springframework.security: WARN
        com.shop: INFO
        org.hibernate.SQL: WARN
        org.hibernate.type.descriptor.sql.BasicBinder: WARN
